# config.yaml
sources:
  - UFO/Tektur.designspace
axisOrder:
  - wdth
  - wght
familyName: "Tektur"
stat:
  - name: Width
    tag: wdth
    values:
    - name: Condensed
      value: 75
    - name: SemiCondensed
      value: 87.5
    - name: Normal
      value: 100
      flags: 2
  - name: Weight
    tag: wght
    values:
    - name: Regular
      value: 400
      linkedValue: 700
      flags: 2
    - name: Medium
      value: 500
    - name: SemiBold
      value: 600
    - name: Bold
      value: 700
    - name: ExtraBold
      value: 800
    - name: Black
      value: 900
buildOTF: false
instances:
  Tektur[wdth,wght].ttf:
    - familyName: "Tektur"
      styleName: "Regular"
      coordinates:
        wdth: 100
        wght: 400
    - familyName: "Tektur"
      styleName: "Medium"
      coordinates:
        wdth: 100
        wght: 500
    - familyName: "Tektur"
      styleName: "SemiBold"
      coordinates:
        wdth: 100
        wght: 600
    - familyName: "Tektur"
      styleName: "Bold"
      coordinates:
        wdth: 100
        wght: 700
    - familyName: "Tektur"
      styleName: "ExtraBold"
      coordinates:
        wdth: 100
        wght: 800
    - familyName: "Tektur"
      styleName: "Black"
      coordinates:
        wdth: 100
        wght: 900
    - familyName: "Tektur SemiCondensed"
      styleName: "Regular"
      coordinates:
        wdth: 87.5
        wght: 400
    - familyName: "Tektur SemiCondensed"
      styleName: "Medium"
      coordinates:
        wdth: 87.5
        wght: 500
    - familyName: "Tektur SemiCondensed"
      styleName: "SemiBold"
      coordinates:
        wdth: 87.5
        wght: 600
    - familyName: "Tektur SemiCondensed"
      styleName: "Bold"
      coordinates:
        wdth: 87.5
        wght: 700
    - familyName: "Tektur SemiCondensed"
      styleName: "ExtraBold"
      coordinates:
        wdth: 87.5
        wght: 800
    - familyName: "Tektur SemiCondensed"
      styleName: "Black"
      coordinates:
        wdth: 87.5
        wght: 900
    - familyName: "Tektur Condensed"
      styleName: "Regular"
      coordinates:
        wdth: 75
        wght: 400
    - familyName: "Tektur Condensed"
      styleName: "Medium"
      coordinates:
        wdth: 75
        wght: 500
    - familyName: "Tektur Condensed"
      styleName: "SemiBold"
      coordinates:
        wdth: 75
        wght: 600
    - familyName: "Tektur Condensed"
      styleName: "Bold"
      coordinates:
        wdth: 75
        wght: 700
    - familyName: "Tektur Condensed"
      styleName: "ExtraBold"
      coordinates:
        wdth: 75
        wght: 800
    - familyName: "Tektur Condensed"
      styleName: "Black"
      coordinates:
        wdth: 75
        wght: 900